name: Go

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.7

    - name: Lint
      run: staticcheck -checks=all ./...

    - name: Test
      run: go test ./... -race -cover
